# fly.toml app configuration file generated for valtrack on 2024-05-20T17:21:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'valtrack'
primary_region = 'ams'

[build]

[[services]]
  internal_port = 9000
  protocol = "tcp"
  
  [[services.ports]]
    port = "9000"

[[services]]
  internal_port = 9000
  protocol = "udp"

  [[services.ports]]
    port = "9000"

  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
